[package]
name = "gimmie_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
futures-util = "0.3.30"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11.5"
lettre = "0.11.7"
lettre_email = "0.9.4"